spring.application.name=Back-End

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/web-shop
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Security ?? test
spring.security.user.name=admin
spring.security.user.password=1234


# jwtSecret , expiration time
spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=172800000


# ? api
spring.security.oauth2.client.registration.github.client-id=Ov23lif8BSYtqi37dCdw
spring.security.oauth2.client.registration.github.client-secret=18536736dd8d7d513615c2499df0551701018127
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# ?? api
spring.security.oauth2.client.registration.google.client-id=172503650497-2814jknc776h5fu58dotch1p45421kud.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
frontend.url=http://localhost:5173

# ??? ?? ?? (??? ??? ?? ??)
file.upload.path=public/images/